### ISSUE TITLE
Can't uninstall this module

### ISSUE THREAD

**Issue by liushuai0929** [Pixel-Props/redfin#3]
I removed the module in magisk, then restarted the phone, and found that the module was not removed.
How can I remove this module?
![Screenshot_20201112-111430](https://user-images.githubusercontent.com/18647361/98892599-a3d4c480-24db-11eb-97a0-b60e2349e62a.png)

**Comment by 0x11DFE** [comment]
Are you using a stable version of Magisk?
I suspect that the issue is due to changing the line ending to unix `\n` instead of using the default DOS line ending `\r\n`.
If the issue is due to [Newline](https://en.wikipedia.org/wiki/Newline) it should be reported to [Magisk](https://github.com/topjohnwu/Magisk/issues).

**Comment by liushuai0929** [comment]
Got it.
I used the canary version.
Thank you for the solution.

**Comment by AadilGillani** [comment]
I am facing the same issue on Redmi Note 8 on Miui and issue isn't fixed

**Comment by 0x11DFE** [comment]
> I am facing the same issue on Redmi Note 8 on Miui and issue isn't fixed

The issue could be happening on [customize.sh](https://github.com/Pixel-Props/redfin/blob/main/customize.sh).
It could only happen if your Magisk has failed loading its [util_functions.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh) during installation or your phone has broken unix tools.
